### ISSUE TITLE
mods are using an outdated configuration for Patchouli books

### ISSUE THREAD

**Issue by Dseelis** [Dseelis/Arcane-CSD-#5]
15:44:45] [Render thread/ERROR]: Failed to load book seasonsextras:seasonal_compendium defined by mod seasonsextras, skipping
java.lang.IllegalArgumentException: Book seasonsextras:seasonal_compendium has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[15:44:45] [Render thread/ERROR]: Failed to load book betternether:betternether_book defined by mod betternether, skipping
java.lang.IllegalArgumentException: Book betternether:betternether_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[patchouli-1.20.1-81-FABRIC-a28f0b30613d05bf.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]

**Comment by Dseelis** [comment]
The error logs indicate that the seasonsextras and betternether mods are using an outdated configuration for Patchouli books, which is causing the game to fail to load these books
